# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ParstaGram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ParstaGram
	pod 'Parse'
	pod 'AlamofireImage'

  target 'ParstaGramTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'ParstaGramUITests' do
    # Pods for testing

  end

end
